/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockserial.h"

static const char* CMockString_SERIAL_PrintLetter = "SERIAL_PrintLetter";
static const char* CMockString_SERIAL_SendMessage = "SERIAL_SendMessage";
static const char* CMockString_SERIAL_SendMessageWithInteger = "SERIAL_SendMessageWithInteger";
static const char* CMockString_SERIAL_Setup = "SERIAL_Setup";
static const char* CMockString_integer = "integer";
static const char* CMockString_pString = "pString";
static const char* CMockString_string_len = "string_len";

typedef struct _CMOCK_SERIAL_PrintLetter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SERIAL_PrintLetter_CALL_INSTANCE;

typedef struct _CMOCK_SERIAL_Setup_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SERIAL_Setup_CALL_INSTANCE;

typedef struct _CMOCK_SERIAL_SendMessage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_pString;
  uint8_t Expected_string_len;

} CMOCK_SERIAL_SendMessage_CALL_INSTANCE;

typedef struct _CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_pString;
  uint8_t Expected_string_len;
  int Expected_integer;

} CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE;

static struct MockserialInstance
{
  CMOCK_MEM_INDEX_TYPE SERIAL_PrintLetter_CallInstance;
  CMOCK_MEM_INDEX_TYPE SERIAL_Setup_CallInstance;
  CMOCK_MEM_INDEX_TYPE SERIAL_SendMessage_CallInstance;
  CMOCK_MEM_INDEX_TYPE SERIAL_SendMessageWithInteger_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockserial_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SERIAL_PrintLetter_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SERIAL_PrintLetter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SERIAL_Setup_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SERIAL_Setup);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SERIAL_SendMessage_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SERIAL_SendMessage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SERIAL_SendMessageWithInteger_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SERIAL_SendMessageWithInteger);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockserial_Init(void)
{
  Mockserial_Destroy();
}

void Mockserial_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SERIAL_PrintLetter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SERIAL_PrintLetter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SERIAL_PrintLetter);
  cmock_call_instance = (CMOCK_SERIAL_PrintLetter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SERIAL_PrintLetter_CallInstance);
  Mock.SERIAL_PrintLetter_CallInstance = CMock_Guts_MemNext(Mock.SERIAL_PrintLetter_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SERIAL_PrintLetter_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SERIAL_PrintLetter_CALL_INSTANCE));
  CMOCK_SERIAL_PrintLetter_CALL_INSTANCE* cmock_call_instance = (CMOCK_SERIAL_PrintLetter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SERIAL_PrintLetter_CallInstance = CMock_Guts_MemChain(Mock.SERIAL_PrintLetter_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void SERIAL_Setup(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SERIAL_Setup_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SERIAL_Setup);
  cmock_call_instance = (CMOCK_SERIAL_Setup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SERIAL_Setup_CallInstance);
  Mock.SERIAL_Setup_CallInstance = CMock_Guts_MemNext(Mock.SERIAL_Setup_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SERIAL_Setup_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SERIAL_Setup_CALL_INSTANCE));
  CMOCK_SERIAL_Setup_CALL_INSTANCE* cmock_call_instance = (CMOCK_SERIAL_Setup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SERIAL_Setup_CallInstance = CMock_Guts_MemChain(Mock.SERIAL_Setup_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void SERIAL_SendMessage(char* pString, uint8_t string_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SERIAL_SendMessage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SERIAL_SendMessage);
  cmock_call_instance = (CMOCK_SERIAL_SendMessage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SERIAL_SendMessage_CallInstance);
  Mock.SERIAL_SendMessage_CallInstance = CMock_Guts_MemNext(Mock.SERIAL_SendMessage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SERIAL_SendMessage,CMockString_pString);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pString, pString, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SERIAL_SendMessage,CMockString_string_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_string_len, string_len, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SERIAL_SendMessage(CMOCK_SERIAL_SendMessage_CALL_INSTANCE* cmock_call_instance, char* pString, uint8_t string_len);
void CMockExpectParameters_SERIAL_SendMessage(CMOCK_SERIAL_SendMessage_CALL_INSTANCE* cmock_call_instance, char* pString, uint8_t string_len)
{
  cmock_call_instance->Expected_pString = pString;
  cmock_call_instance->Expected_string_len = string_len;
}

void SERIAL_SendMessage_CMockExpect(UNITY_LINE_TYPE cmock_line, char* pString, uint8_t string_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SERIAL_SendMessage_CALL_INSTANCE));
  CMOCK_SERIAL_SendMessage_CALL_INSTANCE* cmock_call_instance = (CMOCK_SERIAL_SendMessage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SERIAL_SendMessage_CallInstance = CMock_Guts_MemChain(Mock.SERIAL_SendMessage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SERIAL_SendMessage(cmock_call_instance, pString, string_len);
}

void SERIAL_SendMessageWithInteger(char* pString, uint8_t string_len, int integer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SERIAL_SendMessageWithInteger);
  cmock_call_instance = (CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SERIAL_SendMessageWithInteger_CallInstance);
  Mock.SERIAL_SendMessageWithInteger_CallInstance = CMock_Guts_MemNext(Mock.SERIAL_SendMessageWithInteger_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SERIAL_SendMessageWithInteger,CMockString_pString);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pString, pString, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SERIAL_SendMessageWithInteger,CMockString_string_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_string_len, string_len, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SERIAL_SendMessageWithInteger,CMockString_integer);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_integer, integer, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SERIAL_SendMessageWithInteger(CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE* cmock_call_instance, char* pString, uint8_t string_len, int integer);
void CMockExpectParameters_SERIAL_SendMessageWithInteger(CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE* cmock_call_instance, char* pString, uint8_t string_len, int integer)
{
  cmock_call_instance->Expected_pString = pString;
  cmock_call_instance->Expected_string_len = string_len;
  cmock_call_instance->Expected_integer = integer;
}

void SERIAL_SendMessageWithInteger_CMockExpect(UNITY_LINE_TYPE cmock_line, char* pString, uint8_t string_len, int integer)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE));
  CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE* cmock_call_instance = (CMOCK_SERIAL_SendMessageWithInteger_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SERIAL_SendMessageWithInteger_CallInstance = CMock_Guts_MemChain(Mock.SERIAL_SendMessageWithInteger_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SERIAL_SendMessageWithInteger(cmock_call_instance, pString, string_len, integer);
}

