/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSERIAL_H
#define _MOCKSERIAL_H

#include "unity.h"
#include "serial.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockserial_Init(void);
void Mockserial_Destroy(void);
void Mockserial_Verify(void);




#define SERIAL_PrintLetter_Expect() SERIAL_PrintLetter_CMockExpect(__LINE__)
void SERIAL_PrintLetter_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SERIAL_Setup_Expect() SERIAL_Setup_CMockExpect(__LINE__)
void SERIAL_Setup_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SERIAL_SendMessage_Expect(pString, string_len) SERIAL_SendMessage_CMockExpect(__LINE__, pString, string_len)
void SERIAL_SendMessage_CMockExpect(UNITY_LINE_TYPE cmock_line, char* pString, uint8_t string_len);
#define SERIAL_SendMessageWithInteger_Expect(pString, string_len, integer) SERIAL_SendMessageWithInteger_CMockExpect(__LINE__, pString, string_len, integer)
void SERIAL_SendMessageWithInteger_CMockExpect(UNITY_LINE_TYPE cmock_line, char* pString, uint8_t string_len, int integer);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
